### ISSUE TITLE
Fixture customisation to ignore default values 

### ISSUE THREAD

**Issue by waliahimanshu** [FlexTradeUKLtd/kfixture#10]
When the class has at-least one non-null field (rest with default values), fixture creates random values for all fields in that class.

But, If all fields has default value set to

>  null/ ""/any data

fixture output type object is created with default values. Is there a customisation to ignore default values in this case and have randomised data instead?

Example : 
**Input :** 
```
data class User(val id: String? = null, val desc: String = "", val scheme : String,
                val url: String? = null)

data class Image(
    val id: String? = null,
    val desc: String? = null,
    val scheme: String? = null,
    val url: String? = null
)

```

**Output :** 
```

User(id=fee9549d-2d98-4a7a-842b-41241775da4b, desc=f229d694-5cbb-424a-b243-a20769e87f04, scheme=50328305-fb59-4d28-8c6d-0a699974b0d1, url=6692cce1-e009-4d54-8f11-5fb00274f9fa)

ImageDto(id=null, desc=null, scheme=null, url=null)
```

**Comment by waliahimanshu** [comment]
Thank you @phutchin for fixing this.
kfixture looks nice too.

**Comment by rses** [comment]
Has this been released?

**Comment by phutchin** [comment]
It has now.  0.2.0
