### ISSUE TITLE
Question : creating list<type> with customisation 

### ISSUE THREAD

**Issue by waliahimanshu** [FlexTradeUKLtd/kfixture#14]
Can you please share the example of creating a list of strings with repeat count customisation 
without using @Fixture annotation ?

I tried this, but it gives list with size 0

```
val fixture = KFixture {
            repeatCount(4)
        }
val list: List<String> = fixture()
```

**Comment by phutchin** [comment]
Currently collections aren't supported.
Duplicate of #12

**Comment by phutchin** [comment]
Duplicate of #12
