### ISSUE TITLE
[Question] What does this mean circularDependencyBehaviour().omitSpecimen() ? 

### ISSUE THREAD

**Issue by dss-kenya** [FlexTradeUKLtd/kfixture#15]
Would anyone please help me understand what the following line means? `circularDependencyBehaviour().omitSpecimen()` ?

**Comment by TWiStErRob** [comment]
Think about recursive structures:
```java
class Person {
    Person(String name, Person parent) {
    }
}
```
if you create this with JFixture you'll get an error.
With `omitSpecimen` it'll actually create an instance:
```java
new Person("fixtured string", null /* specimen omitted */)
```

**Comment by dss-kenya** [comment]
Thank you very much for the simple explanation. Understood it quite well.
